parameters:
  # ...
  mailer.transport: sendmail

services:
  manager:
    class: \Illuminate\Database\Capsule\Manager
    #arguments: ['%mailer.transport%']
    calls:

      - [addConnection,
         [
           {
             driver: 'mysql',
             host: 'mysqlservice',
             database: 'simpleBookingLedger',
             username: 'root',
             password: 'root',
             charset: 'utf8',
             collation: 'utf8_unicode_ci',
             prefix: '',
           }
         ]]
      - [setAsGlobal,[]]
