parameters:
  # ...
  mailer.transport: sendmail

services:
  manager:
    # uses laravel data access object in symphony dependency injection
    class: \Illuminate\Database\Capsule\Manager
    #arguments: ['%mailer.transport%']
    calls:
      - [addConnection,
         [
           {
             driver: 'mysql',
             host: 'mysqlservice',
             database: 'simpleBookingLedger',
             username: 'root',
             password: 'root',
             charset: 'utf8',
             collation: 'utf8_unicode_ci',
             prefix: '',
           }
         ]]
      - [setAsGlobal,[]]
#  @TODO:
#  entityManager:
#    # uses laravel data access object in symphony dependency injection
#    class: \Doctrine\ORM\EntityManager;
#    #arguments: ['%mailer.transport%']
#    calls:
#      - [create,
#         [
#         {
#           driver: 'pdo_mysql',
#           host: 'mysqlservice',
#           database: 'simpleBookingLedger',
#           username: 'root',
#           password: 'root'
#         },
#         # needs a config originating as a return result from another function call like Nette
#         ]]
#      - [setAsGlobal,[]]
